FROM hashicorp/terraform:light

ARG COMMIT_HASH
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_ACCESS_KEY_ID
ARG AWS_DEFAULT_REGION

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

COPY terraform /terraform

# Create deploy plan
WORKDIR /terraform
RUN terraform init
RUN terraform plan \
-out=terraform.${COMMIT_HASH}.tfplan \
-refresh=true \
-var="tag=${COMMIT_HASH}"

